using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SpaceEngineersScripts.Utilities
{
    internal class CraftingQueueDisplayStringToInternal
    {
        private Dictionary<string, string> displayToInternal = new Dictionary<string, string>()
        {
            { "Artillery Shell", "MyObjectBuilder_BlueprintDefinition/Position0120_LargeCalibreAmmo" },
            { "Assault Cannon Shell", "MyObjectBuilder_BlueprintDefinition/Position0110_MediumCalibreAmmo" },
            { "Autocannon Magazine", "MyObjectBuilder_BlueprintDefinition/Position0090_AutocannonClip" },
            { "Bulletproof Glass", "MyObjectBuilder_BlueprintDefinition/BulletproofGlass" },
            { "Canvas", "MyObjectBuilder_BlueprintDefinition/Position0030_Canvas" },
            { "Cobalt Ingot", "MyObjectBuilder_BlueprintDefinition/CobaltOreToIngot" },
            { "Computer", "MyObjectBuilder_BlueprintDefinition/ComputerComponent" },
            { "Construction Comp.", "MyObjectBuilder_BlueprintDefinition/ConstructionComponent" },
            { "Datapad", "MyObjectBuilder_BlueprintDefinition/Position0040_Datapad" },
            { "Detector Comp.", "MyObjectBuilder_BlueprintDefinition/DetectorComponent" },
            { "Display", "MyObjectBuilder_BlueprintDefinition/Display" },
            { "DisplayName_Item_EngineerPlushie", "MyObjectBuilder_BlueprintDefinition/EngineerPlushie" },
            { "DisplayName_Item_SabiroidPlushie", "MyObjectBuilder_BlueprintDefinition/SabiroidPlushie" },
            { "Elite Grinder", "MyObjectBuilder_BlueprintDefinition/Position0040_AngleGrinder4" },
            { "Elite Hand Drill", "MyObjectBuilder_BlueprintDefinition/Position0080_HandDrill4" },
            { "Elite Welder", "MyObjectBuilder_BlueprintDefinition/Position0120_Welder4" },
            { "Enhanced Grinder", "MyObjectBuilder_BlueprintDefinition/Position0020_AngleGrinder2" },
            { "Enhanced Hand Drill", "MyObjectBuilder_BlueprintDefinition/Position0060_HandDrill2" },
            { "Enhanced Welder", "MyObjectBuilder_BlueprintDefinition/Position0100_Welder2" },
            { "Explosives", "MyObjectBuilder_BlueprintDefinition/ExplosivesComponent" },
            { "Fireworks Blue", "MyObjectBuilder_BlueprintDefinition/Position0007_FireworksBoxBlue" },
            { "Fireworks Green", "MyObjectBuilder_BlueprintDefinition/Position00071_FireworksBoxGreen" },
            { "Fireworks Pink", "MyObjectBuilder_BlueprintDefinition/Position00074_FireworksBoxPink" },
            { "Fireworks Rainbow", "MyObjectBuilder_BlueprintDefinition/Position00075_FireworksBoxRainbow" },
            { "Fireworks Red", "MyObjectBuilder_BlueprintDefinition/Position00072_FireworksBoxRed" },
            { "Fireworks Yellow", "MyObjectBuilder_BlueprintDefinition/Position00073_FireworksBoxYellow" },
            { "Flare Gun", "MyObjectBuilder_BlueprintDefinition/Position0005_FlareGun" },
            { "Flare Gun Clip", "MyObjectBuilder_BlueprintDefinition/Position0005_FlareGunMagazine" },
            { "Gatling Ammo Box", "MyObjectBuilder_BlueprintDefinition/Position0080_NATO_25x184mmMagazine" },
            { "Girder", "MyObjectBuilder_BlueprintDefinition/GirderComponent" },
            { "Gold Ingot", "MyObjectBuilder_BlueprintDefinition/GoldOreToIngot" },
            { "Gravel", "MyObjectBuilder_BlueprintDefinition/StoneOreToIngot_Deconstruction" },
            { "Gravity Comp.", "MyObjectBuilder_BlueprintDefinition/GravityGeneratorComponent" },
            { "Grinder", "MyObjectBuilder_BlueprintDefinition/Position0010_AngleGrinder" },
            { "Hand Drill", "MyObjectBuilder_BlueprintDefinition/Position0050_HandDrill" },
            { "Hydrogen Bottle", "MyObjectBuilder_BlueprintDefinition/Position0020_HydrogenBottle" },
            { "Hydrogen Bottles", "MyObjectBuilder_BlueprintDefinition/HydrogenBottlesRefill" },
            { "Ingots", "MyObjectBuilder_BlueprintDefinition/StoneOreToIngot" },
            { "Ingots", "MyObjectBuilder_BlueprintDefinition/Position0010_StoneOreToIngotBasic" },
            { "Interior Plate", "MyObjectBuilder_BlueprintDefinition/InteriorPlate" },
            { "Iron Ingot", "MyObjectBuilder_BlueprintDefinition/IronOreToIngot" },
            { "Iron Ingot", "MyObjectBuilder_BlueprintDefinition/ScrapIngotToIronIngot" },
            { "Iron Ingot", "MyObjectBuilder_BlueprintDefinition/ScrapToIronIngot" },
            { "Large Railgun Sabot", "MyObjectBuilder_BlueprintDefinition/Position0140_LargeRailgunAmmo" },
            { "Large Steel Tube", "MyObjectBuilder_BlueprintDefinition/LargeTube" },
            { "Magnesium Powder", "MyObjectBuilder_BlueprintDefinition/MagnesiumOreToIngot" },
            { "Medical Comp.", "MyObjectBuilder_BlueprintDefinition/MedicalComponent" },
            { "Metal Grid", "MyObjectBuilder_BlueprintDefinition/MetalGrid" },
            { "Motor", "MyObjectBuilder_BlueprintDefinition/MotorComponent" },
            { "MR-20 Rifle", "MyObjectBuilder_BlueprintDefinition/Position0040_AutomaticRifle" },
            { "MR-20 Rifle Magazine", "MyObjectBuilder_BlueprintDefinition/Position0040_AutomaticRifleGun_Mag_20rd" },
            { "MR-30E Rifle", "MyObjectBuilder_BlueprintDefinition/Position0070_UltimateAutomaticRifle" },
            { "MR-30E Rifle Magazine", "MyObjectBuilder_BlueprintDefinition/Position0070_UltimateAutomaticRifleGun_Mag_30rd" },
            { "MR-50A Rifle", "MyObjectBuilder_BlueprintDefinition/Position0050_RapidFireAutomaticRifle" },
            { "MR-50A Rifle Magazine", "MyObjectBuilder_BlueprintDefinition/Position0050_RapidFireAutomaticRifleGun_Mag_50rd" },
            { "MR-8P Rifle", "MyObjectBuilder_BlueprintDefinition/Position0060_PreciseAutomaticRifle" },
            { "MR-8P Rifle Magazine", "MyObjectBuilder_BlueprintDefinition/Position0060_PreciseAutomaticRifleGun_Mag_5rd" },
            { "Nickel Ingot", "MyObjectBuilder_BlueprintDefinition/NickelOreToIngot" },
            { "Oxygen", "MyObjectBuilder_BlueprintDefinition/IceToOxygen" },
            { "Oxygen Bottle", "MyObjectBuilder_BlueprintDefinition/Position0010_OxygenBottle" },
            { "Oxygen Bottles", "MyObjectBuilder_BlueprintDefinition/OxygenBottlesRefill" },
            { "Platinum Ingot", "MyObjectBuilder_BlueprintDefinition/PlatinumOreToIngot" },
            { "Power Cell", "MyObjectBuilder_BlueprintDefinition/PowerCell" },
            { "PRO-1 Rocket Launcher", "MyObjectBuilder_BlueprintDefinition/Position0090_AdvancedHandHeldLauncher" },
            { "Proficient Grinder", "MyObjectBuilder_BlueprintDefinition/Position0030_AngleGrinder3" },
            { "Proficient Hand Drill", "MyObjectBuilder_BlueprintDefinition/Position0070_HandDrill3" },
            { "Proficient Welder", "MyObjectBuilder_BlueprintDefinition/Position0110_Welder3" },
            { "Radio-comm Comp.", "MyObjectBuilder_BlueprintDefinition/RadioCommunicationComponent" },
            { "Reactor Comp.", "MyObjectBuilder_BlueprintDefinition/ReactorComponent" },
            { "RO-1 Rocket Launcher", "MyObjectBuilder_BlueprintDefinition/Position0080_BasicHandHeldLauncher" },
            { "Rocket", "MyObjectBuilder_BlueprintDefinition/Position0100_Missile200mm" },
            { "S-10 Pistol", "MyObjectBuilder_BlueprintDefinition/Position0010_SemiAutoPistol" },
            { "S-10 Pistol Magazine", "MyObjectBuilder_BlueprintDefinition/Position0010_SemiAutoPistolMagazine" },
            { "S-10E Pistol", "MyObjectBuilder_BlueprintDefinition/Position0030_EliteAutoPistol" },
            { "S-10E Pistol Magazine", "MyObjectBuilder_BlueprintDefinition/Position0030_ElitePistolMagazine" },
            { "S-20A Pistol", "MyObjectBuilder_BlueprintDefinition/Position0020_FullAutoPistol" },
            { "S-20A Pistol Magazine", "MyObjectBuilder_BlueprintDefinition/Position0020_FullAutoPistolMagazine" },
            { "Silicon Wafer", "MyObjectBuilder_BlueprintDefinition/SiliconOreToIngot" },
            { "Silver Ingot", "MyObjectBuilder_BlueprintDefinition/SilverOreToIngot" },
            { "Small Railgun Sabot", "MyObjectBuilder_BlueprintDefinition/Position0130_SmallRailgunAmmo" },
            { "Small Steel Tube", "MyObjectBuilder_BlueprintDefinition/SmallTube" },
            { "Solar Cell", "MyObjectBuilder_BlueprintDefinition/SolarCell" },
            { "Steel Plate", "MyObjectBuilder_BlueprintDefinition/SteelPlate" },
            { "Superconductor", "MyObjectBuilder_BlueprintDefinition/Superconductor" },
            { "Thruster Comp.", "MyObjectBuilder_BlueprintDefinition/ThrustComponent" },
            { "Uranium Ingot", "MyObjectBuilder_BlueprintDefinition/UraniumOreToIngot" },
            { "Welder", "MyObjectBuilder_BlueprintDefinition/Position0090_Welder" },
            { "Zone Chip", "MyObjectBuilder_BlueprintDefinition/ZoneChip" },
        };

        private Dictionary<string, string> internalToDisplay = new Dictionary<string, string>()
        {
            { "MyObjectBuilder_BlueprintDefinition/Position0120_LargeCalibreAmmo", "Artillery Shell" },
            { "MyObjectBuilder_BlueprintDefinition/Position0110_MediumCalibreAmmo", "Assault Cannon Shell" },
            { "MyObjectBuilder_BlueprintDefinition/Position0090_AutocannonClip", "Autocannon Magazine" },
            { "MyObjectBuilder_BlueprintDefinition/BulletproofGlass", "Bulletproof Glass" },
            { "MyObjectBuilder_BlueprintDefinition/Position0030_Canvas", "Canvas" },
            { "MyObjectBuilder_BlueprintDefinition/CobaltOreToIngot", "Cobalt Ingot" },
            { "MyObjectBuilder_BlueprintDefinition/ComputerComponent", "Computer" },
            { "MyObjectBuilder_BlueprintDefinition/ConstructionComponent", "Construction Comp." },
            { "MyObjectBuilder_BlueprintDefinition/Position0040_Datapad", "Datapad" },
            { "MyObjectBuilder_BlueprintDefinition/DetectorComponent", "Detector Comp." },
            { "MyObjectBuilder_BlueprintDefinition/Display", "Display" },
            { "MyObjectBuilder_BlueprintDefinition/EngineerPlushie", "DisplayName_Item_EngineerPlushie" },
            { "MyObjectBuilder_BlueprintDefinition/SabiroidPlushie", "DisplayName_Item_SabiroidPlushie" },
            { "MyObjectBuilder_BlueprintDefinition/Position0040_AngleGrinder4", "Elite Grinder" },
            { "MyObjectBuilder_BlueprintDefinition/Position0080_HandDrill4", "Elite Hand Drill" },
            { "MyObjectBuilder_BlueprintDefinition/Position0120_Welder4", "Elite Welder" },
            { "MyObjectBuilder_BlueprintDefinition/Position0020_AngleGrinder2", "Enhanced Grinder" },
            { "MyObjectBuilder_BlueprintDefinition/Position0060_HandDrill2", "Enhanced Hand Drill" },
            { "MyObjectBuilder_BlueprintDefinition/Position0100_Welder2", "Enhanced Welder" },
            { "MyObjectBuilder_BlueprintDefinition/ExplosivesComponent", "Explosives" },
            { "MyObjectBuilder_BlueprintDefinition/Position0007_FireworksBoxBlue", "Fireworks Blue" },
            { "MyObjectBuilder_BlueprintDefinition/Position00071_FireworksBoxGreen", "Fireworks Green" },
            { "MyObjectBuilder_BlueprintDefinition/Position00074_FireworksBoxPink", "Fireworks Pink" },
            { "MyObjectBuilder_BlueprintDefinition/Position00075_FireworksBoxRainbow", "Fireworks Rainbow" },
            { "MyObjectBuilder_BlueprintDefinition/Position00072_FireworksBoxRed", "Fireworks Red" },
            { "MyObjectBuilder_BlueprintDefinition/Position00073_FireworksBoxYellow", "Fireworks Yellow" },
            { "MyObjectBuilder_BlueprintDefinition/Position0005_FlareGun", "Flare Gun" },
            { "MyObjectBuilder_BlueprintDefinition/Position0005_FlareGunMagazine", "Flare Gun Clip" },
            { "MyObjectBuilder_BlueprintDefinition/Position0080_NATO_25x184mmMagazine", "Gatling Ammo Box" },
            { "MyObjectBuilder_BlueprintDefinition/GirderComponent", "Girder" },
            { "MyObjectBuilder_BlueprintDefinition/GoldOreToIngot", "Gold Ingot" },
            { "MyObjectBuilder_BlueprintDefinition/StoneOreToIngot_Deconstruction", "Gravel" },
            { "MyObjectBuilder_BlueprintDefinition/GravityGeneratorComponent", "Gravity Comp." },
            { "MyObjectBuilder_BlueprintDefinition/Position0010_AngleGrinder", "Grinder" },
            { "MyObjectBuilder_BlueprintDefinition/Position0050_HandDrill", "Hand Drill" },
            { "MyObjectBuilder_BlueprintDefinition/Position0020_HydrogenBottle", "Hydrogen Bottle" },
            { "MyObjectBuilder_BlueprintDefinition/HydrogenBottlesRefill", "Hydrogen Bottles" },
            { "MyObjectBuilder_BlueprintDefinition/StoneOreToIngot", "Ingots" },
            { "MyObjectBuilder_BlueprintDefinition/Position0010_StoneOreToIngotBasic", "Ingots" },
            { "MyObjectBuilder_BlueprintDefinition/InteriorPlate", "Interior Plate" },
            { "MyObjectBuilder_BlueprintDefinition/IronOreToIngot", "Iron Ingot" },
            { "MyObjectBuilder_BlueprintDefinition/ScrapIngotToIronIngot", "Iron Ingot" },
            { "MyObjectBuilder_BlueprintDefinition/ScrapToIronIngot", "Iron Ingot" },
            { "MyObjectBuilder_BlueprintDefinition/Position0140_LargeRailgunAmmo", "Large Railgun Sabot" },
            { "MyObjectBuilder_BlueprintDefinition/LargeTube", "Large Steel Tube" },
            { "MyObjectBuilder_BlueprintDefinition/MagnesiumOreToIngot", "Magnesium Powder" },
            { "MyObjectBuilder_BlueprintDefinition/MedicalComponent", "Medical Comp." },
            { "MyObjectBuilder_BlueprintDefinition/MetalGrid", "Metal Grid" },
            { "MyObjectBuilder_BlueprintDefinition/MotorComponent", "Motor" },
            { "MyObjectBuilder_BlueprintDefinition/Position0040_AutomaticRifle", "MR-20 Rifle" },
            { "MyObjectBuilder_BlueprintDefinition/Position0040_AutomaticRifleGun_Mag_20rd", "MR-20 Rifle Magazine" },
            { "MyObjectBuilder_BlueprintDefinition/Position0070_UltimateAutomaticRifle", "MR-30E Rifle" },
            { "MyObjectBuilder_BlueprintDefinition/Position0070_UltimateAutomaticRifleGun_Mag_30rd", "MR-30E Rifle Magazine" },
            { "MyObjectBuilder_BlueprintDefinition/Position0050_RapidFireAutomaticRifle", "MR-50A Rifle" },
            { "MyObjectBuilder_BlueprintDefinition/Position0050_RapidFireAutomaticRifleGun_Mag_50rd", "MR-50A Rifle Magazine" },
            { "MyObjectBuilder_BlueprintDefinition/Position0060_PreciseAutomaticRifle", "MR-8P Rifle" },
            { "MyObjectBuilder_BlueprintDefinition/Position0060_PreciseAutomaticRifleGun_Mag_5rd", "MR-8P Rifle Magazine" },
            { "MyObjectBuilder_BlueprintDefinition/NickelOreToIngot", "Nickel Ingot" },
            { "MyObjectBuilder_BlueprintDefinition/IceToOxygen", "Oxygen" },
            { "MyObjectBuilder_BlueprintDefinition/Position0010_OxygenBottle", "Oxygen Bottle" },
            { "MyObjectBuilder_BlueprintDefinition/OxygenBottlesRefill", "Oxygen Bottles" },
            { "MyObjectBuilder_BlueprintDefinition/PlatinumOreToIngot", "Platinum Ingot" },
            { "MyObjectBuilder_BlueprintDefinition/PowerCell", "Power Cell" },
            { "MyObjectBuilder_BlueprintDefinition/Position0090_AdvancedHandHeldLauncher", "PRO-1 Rocket Launcher" },
            { "MyObjectBuilder_BlueprintDefinition/Position0030_AngleGrinder3", "Proficient Grinder" },
            { "MyObjectBuilder_BlueprintDefinition/Position0070_HandDrill3", "Proficient Hand Drill" },
            { "MyObjectBuilder_BlueprintDefinition/Position0110_Welder3", "Proficient Welder" },
            { "MyObjectBuilder_BlueprintDefinition/RadioCommunicationComponent", "Radio-comm Comp." },
            { "MyObjectBuilder_BlueprintDefinition/ReactorComponent", "Reactor Comp." },
            { "MyObjectBuilder_BlueprintDefinition/Position0080_BasicHandHeldLauncher", "RO-1 Rocket Launcher" },
            { "MyObjectBuilder_BlueprintDefinition/Position0100_Missile200mm", "Rocket" },
            { "MyObjectBuilder_BlueprintDefinition/Position0010_SemiAutoPistol", "S-10 Pistol" },
            { "MyObjectBuilder_BlueprintDefinition/Position0010_SemiAutoPistolMagazine", "S-10 Pistol Magazine" },
            { "MyObjectBuilder_BlueprintDefinition/Position0030_EliteAutoPistol", "S-10E Pistol" },
            { "MyObjectBuilder_BlueprintDefinition/Position0030_ElitePistolMagazine", "S-10E Pistol Magazine" },
            { "MyObjectBuilder_BlueprintDefinition/Position0020_FullAutoPistol", "S-20A Pistol" },
            { "MyObjectBuilder_BlueprintDefinition/Position0020_FullAutoPistolMagazine", "S-20A Pistol Magazine" },
            { "MyObjectBuilder_BlueprintDefinition/SiliconOreToIngot", "Silicon Wafer" },
            { "MyObjectBuilder_BlueprintDefinition/SilverOreToIngot", "Silver Ingot" },
            { "MyObjectBuilder_BlueprintDefinition/Position0130_SmallRailgunAmmo", "Small Railgun Sabot" },
            { "MyObjectBuilder_BlueprintDefinition/SmallTube", "Small Steel Tube" },
            { "MyObjectBuilder_BlueprintDefinition/SolarCell", "Solar Cell" },
            { "MyObjectBuilder_BlueprintDefinition/SteelPlate", "Steel Plate" },
            { "MyObjectBuilder_BlueprintDefinition/Superconductor", "Superconductor" },
            { "MyObjectBuilder_BlueprintDefinition/ThrustComponent", "Thruster Comp." },
            { "MyObjectBuilder_BlueprintDefinition/UraniumOreToIngot", "Uranium Ingot" },
            { "MyObjectBuilder_BlueprintDefinition/Position0090_Welder", "Welder" },
            { "MyObjectBuilder_BlueprintDefinition/ZoneChip", "Zone Chip" },
        };
    }
}
